### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by Research-Code-123** [xhanxu/Mamba3D#15]
Dear author:

Have you ever met this bug?

Mamba3D# bash script/run_scratch.sh
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from tools import pretrain_run_net as pretrain
  File "/root/Documents/Mamba/Mamba3D/tools/__init__.py", line 2, in <module>
    from .runner import test_net
  File "/root/Documents/Mamba/Mamba3D/tools/runner.py", line 5, in <module>
    from tools import builder
  File "/root/Documents/Mamba/Mamba3D/tools/builder.py", line 8, in <module>
    from models import build_model_from_cfg
  File "/root/Documents/Mamba/Mamba3D/models/__init__.py", line 2, in <module>
    import models.Mamba3D
  File "/root/Documents/Mamba/Mamba3D/models/Mamba3D.py", line 34, in <module>
    from .bimamba_ssm.modules.mamba_simple import Mamba
  File "/root/Documents/Mamba/Mamba3D/models/bimamba_ssm/modules/mamba_simple.py", line 21, in <module>
    from ops.selective_scan_interface import selective_scan_fn, mamba_inner_fn, bimamba_inner_fn, mamba_inner_fn_no_out_proj
ModuleNotFoundError: No module named 'ops'

Thanks

**Comment by navvye** [comment]
I'm running into the same error.

**Comment by xhanxu** [comment]
Sorry for the late reply. I think it might be a path error. For example, you may need to modify the path in the following code, and also check if there are similar path errors in other files.
https://github.com/xhanxu/Mamba3D/blob/077fd1ef95da2fa6318a4e7aa7b992c0aa9af778/models/bimamba_ssm/modules/mamba_simple.py#L20-L21
