### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by Research-Code-123** [xhanxu/Mamba3D#17]
Dear Author:

Have you ever met this bug?

Traceback (most recent call last):
  File "main.py", line 100, in <module>
    main()
  File "main.py", line 96, in main
    pretrain(args, config, train_writer, val_writer)
  File "/workspace/Documents/Mamba/Mamba3D/tools/runner_pretrain.py", line 61, in run_net
    base_model = builder.model_builder(config.model)
  File "/workspace/Documents/Mamba/Mamba3D/tools/builder.py", line 34, in model_builder
    model = build_model_from_cfg(config)
  File "/workspace/Documents/Mamba/Mamba3D/models/build_fn.py", line 17, in build_model_from_cfg
    return MODELS.build(cfg, **kwargs)
  File "/workspace/Documents/Mamba/Mamba3D/utils/registry.py", line 147, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/workspace/Documents/Mamba/Mamba3D/utils/registry.py", line 277, in build_from_cfg
    raise KeyError(
KeyError: 'Point_MAE is not in the models registry'
(mamba3d) root@4471b3c8b95f:/workspace/Documents/Mamba/Mamba3D# bash script/run_pretrain.sh

Thanks

**Comment by xhanxu** [comment]
Please refer to https://github.com/xhanxu/Mamba3D/issues/14
